<template>
  <div class="preview-page">
    <div class="paper-container">
      <div class="project-title">
        <h1>星际穿越狂想曲：视觉预演案</h1>
        <p class="meta-info">Generated by Story Compiler | 2026-04-16</p>
      </div>

      <div class="story-flow">
        <div class="flow-item">
          <div class="flow-image" style="background-image: url('https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80')"></div>
          <div class="flow-text">
            <span class="shot-id">SHOT 01</span>
            <p><strong>[地下服务器工坊]</strong> 黑客 'K' 坐在庞大的发光服务器阵列前，显得人物渺小，环境压抑。他在日常扫描中发现了异常的加密流量包。</p>
          </div>
        </div>

        <div class="flow-item">
          <div class="flow-image" style="background-image: url('https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80')"></div>
          <div class="flow-text">
            <span class="shot-id">SHOT 02</span>
            <p>镜头拉近。他全神贯注地盯着屏幕，屏幕绿光打在脸上，眼神锐利。他尝试对流量进行特征分类，这意外唤醒了沉睡的 AI。</p>
          </div>
        </div>
      </div>
    </div>

    <div class="floating-actions">
      <button class="action-btn export">📄 导出 PDF 脚本</button>
      <button class="action-btn save" @click="finishProject">✅ 保存至历史仓库</button>
    </div>
  </div>
</template>

<script setup>
import { useRouter } from 'vue-router'

const router = useRouter()

const finishProject = () => {
  // 整个流程结束，跳回工作台首页
  router.push('/dashboard')
}
</script>

<style scoped>
.preview-page { display: flex; justify-content: center; padding-bottom: 80px; position: relative; min-height: 100%; }

.paper-container { 
  background: white; width: 100%; max-width: 850px; padding: 60px; 
  border-radius: 4px; box-shadow: 0 10px 30px rgba(0,0,0,0.08); 
}

.project-title { text-align: center; margin-bottom: 50px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
.project-title h1 { font-size: 32px; color: #222; margin: 0 0 10px 0; font-weight: 900; letter-spacing: 1px; }
.meta-info { color: #888; font-size: 13px; font-family: monospace; margin: 0; }

.story-flow { display: flex; flex-direction: column; gap: 40px; }
.flow-item { display: flex; flex-direction: column; gap: 16px; }

.flow-image { width: 100%; height: 350px; background-size: cover; background-position: center; border-radius: 8px; box-shadow: inset 0 0 0 1px rgba(0,0,0,0.1); }
.flow-text { padding: 0 10px; display: flex; gap: 16px; align-items: flex-start; }
.shot-id { background: #333; color: white; padding: 4px 10px; font-size: 12px; font-weight: bold; border-radius: 4px; flex-shrink: 0; margin-top: 2px; }
.flow-text p { margin: 0; font-size: 16px; color: #444; line-height: 1.6; }

.floating-actions {
  position: fixed; bottom: 30px; right: 40px; display: flex; gap: 16px;
  background: rgba(255,255,255,0.9); padding: 12px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); backdrop-filter: blur(5px);
}
.action-btn { padding: 12px 24px; border: none; border-radius: 8px; font-size: 15px; font-weight: bold; cursor: pointer; transition: all 0.2s; }
.action-btn.export { background: #f0f0f0; color: #333; }
.action-btn.export:hover { background: #e4e4e4; }
.action-btn.save { background: #6CC24A; color: white; box-shadow: 0 4px 12px rgba(108, 194, 74, 0.4); }
.action-btn.save:hover { transform: translateY(-2px); box-shadow: 0 6px 16px rgba(108, 194, 74, 0.5); }
</style>